import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <article className="prose-legal">
      <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last Updated: March 2026
      </p>

      <p className="mt-6 text-muted-foreground">
        Before using the GeoFast website and services (&quot;Platform&quot;)
        operated from Shenzhen, China, please read these Terms of Service
        (&quot;Terms&quot;) carefully. By accessing or using the Platform, you
        agree to be bound by these Terms.
      </p>

      <Section title="1. Service Description">
        <p>
          GeoFast provides an AI-powered Generative Engine Optimization (GEO)
          audit service. Users submit website URLs, and our system analyzes
          the site&apos;s readiness for AI search engines — including AI
          crawlability, structured data, content citability, and overall AI
          discoverability.
        </p>
      </Section>

      <Section title="2. Pricing and Subscription">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            <strong>Trial (no account):</strong> 3 free scans, lifetime limit.
          </li>
          <li>
            <strong>Free Plan (signed in):</strong> 5 scans per month, resets
            every 30 days.
          </li>
          <li>
            <strong>Pro Plan:</strong> $9.9/month, 300 scans per month, unlimited
            scan history.
          </li>
          <li>
            Subscriptions automatically renew each month. You may cancel at any
            time.
          </li>
          <li>
            Upon cancellation, your Pro access continues until the end of the
            current billing period.
          </li>
          <li>
            Scan credits do not accumulate — unused credits expire at the end
            of each billing cycle.
          </li>
        </ul>
      </Section>

      <Section title="3. Accounts">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            Accounts are created via Google OAuth. You are responsible for
            maintaining the security of your account.
          </li>
          <li>Sharing accounts or reselling the service is prohibited.</li>
          <li>
            You must notify us immediately if you become aware of unauthorized
            use of your account.
          </li>
        </ul>
      </Section>

      <Section title="4. Acceptable Use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Use the service for any unlawful purpose</li>
          <li>Attempt to circumvent usage limits or access restrictions</li>
          <li>
            Abuse the API or submit automated bulk requests beyond your plan
            limits
          </li>
          <li>Interfere with or disrupt the service infrastructure</li>
        </ul>
      </Section>

      <Section title="5. Intellectual Property">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            The GeoFast brand, code, and interface design are our exclusive
            property.
          </li>
          <li>
            You retain full ownership of the websites you scan and the content
            therein.
          </li>
          <li>
            Scan report data generated by our service belongs to you and may be
            exported or shared at your discretion.
          </li>
        </ul>
      </Section>

      <Section title="6. Disclaimer">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            The service is provided on an &quot;AS IS&quot; and &quot;AS
            AVAILABLE&quot; basis without warranties of any kind.
          </li>
          <li>
            AI-generated analysis and recommendations are for informational
            purposes only and do not constitute professional SEO advice.
          </li>
          <li>
            We do not guarantee the accuracy, completeness, or reliability of
            scan results.
          </li>
        </ul>
      </Section>

      <Section title="7. Limitation of Liability">
        <p>
          To the maximum extent permitted by law, GeoFast and its operators
          shall not be liable for any indirect, incidental, special, or
          consequential damages. Our total liability shall not exceed the
          amount you paid us in the 12 months preceding the claim.
        </p>
      </Section>

      <Section title="8. Termination">
        <ul className="list-disc space-y-2 pl-5">
          <li>
            We reserve the right to suspend or terminate accounts that violate
            these Terms.
          </li>
          <li>
            You may stop using the service and cancel your subscription at any
            time.
          </li>
          <li>
            Upon termination, your right to access the service will cease
            immediately (or at the end of the current billing period for paid
            subscriptions).
          </li>
        </ul>
      </Section>

      <Section title="9. Governing Law">
        <p>
          These Terms shall be governed by and construed in accordance with the
          laws of the People&apos;s Republic of China. Any disputes arising
          from these Terms shall be submitted to the jurisdiction of the courts
          in Shenzhen, China.
        </p>
      </Section>

      <Section title="10. Changes">
        <p>
          We reserve the right to modify these Terms. Material changes will be
          communicated at least 30 days in advance via email or notice on our
          website. Continued use after the effective date constitutes
          acceptance of the revised Terms.
        </p>
      </Section>

      <Section title="11. Contact Us">
        <p>
          If you have questions about these Terms, please contact us at:
        </p>
        <p className="mt-2">
          <strong>Email:</strong>{" "}
          <a href="mailto:Marcus.tang@plaud.ai" className="text-primary hover:underline">
            Marcus.tang@plaud.ai
          </a>
        </p>
        <p>
          <strong>Location:</strong> Shenzhen, China
        </p>
      </Section>
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold text-foreground">{title}</h2>
      <div className="mt-4 space-y-3 text-sm leading-relaxed text-muted-foreground">
        {children}
      </div>
    </section>
  );
}
