import type { StoredReport, Issue, PassedCheck, LLMPerspective, EEAT } from "@/lib/types";

function formatIssues(issues: Issue[]): string[] {
  if (issues.length === 0) return ["  No issues found."];
  return issues.map(
    (i, idx) =>
      `  ${idx + 1}. [${i.severity.toUpperCase()}] ${i.title}\n` +
      `     Category: ${i.category} | Dimension: ${i.dimension}\n` +
      `     ${i.description}\n` +
      (i.steps.length > 0
        ? `     Fix:\n${i.steps.map((s, j) => `       ${j + 1}. ${s}`).join("\n")}\n`
        : "")
  );
}

function formatPassed(passed: PassedCheck[]): string[] {
  if (passed.length === 0) return ["  No checks passed."];
  return passed.map((p) => `  ✓ ${p.name} (${p.category})`);
}

function formatAIPerspective(llm: LLMPerspective | null): string[] {
  if (!llm) return ["  AI perspective not available for this scan."];

  const lines: string[] = [
    `  Brand: ${llm.brandOverview.name}`,
    `  Type:  ${llm.brandOverview.businessType}`,
    `  For:   ${llm.brandOverview.targetUsers}`,
    `  AI Citation Score: ${llm.citationScore}/10 — ${llm.citationReasoning}`,
    ``,
    `  Strengths:`,
    ...llm.strengths.map((s) => `    + ${s}`),
    ``,
    `  Weaknesses:`,
    ...llm.weaknesses.map((w) => `    - ${w}`),
    ``,
    `  AI Clearly Understands:`,
    ...llm.aiUnderstanding.clearlyUnderstood.map((t) => `    ✓ ${t}`),
    `  AI Is Confused About:`,
    ...llm.aiUnderstanding.confused.map((t) => `    ? ${t}`),
    `  AI Cannot Find:`,
    ...llm.aiUnderstanding.missing.map((t) => `    ✗ ${t}`),
    ``,
    `  Recommendations:`,
    ...llm.recommendations.map((r, i) => `    ${i + 1}. ${r}`),
  ];
  return lines;
}

function formatEEAT(eeat: EEAT | undefined): string[] {
  if (!eeat) return ["  E-E-A-T assessment not available."];
  const dims = [
    { label: "Experience", data: eeat.experience },
    { label: "Expertise", data: eeat.expertise },
    { label: "Authority", data: eeat.authority },
    { label: "Trust", data: eeat.trust },
  ];
  const total = dims.reduce((s, d) => s + d.data.score, 0);
  return [
    `  Total: ${total}/100`,
    ``,
    ...dims.flatMap((d) => [
      `  ${d.label}: ${d.data.score}/25`,
      `    Evidence: ${d.data.evidence}`,
      `    Gaps:     ${d.data.gaps}`,
    ]),
  ];
}

export function generateReportTxt(report: StoredReport): string {
  const r = report.scanResult;
  const signals = [
    `robots.txt: ${r.domainSignals.robotsTxt ? "Found" : "Missing"}`,
    `llms.txt:   ${r.domainSignals.llmsTxt ? "Found" : "Missing"}`,
    `sitemap:    ${r.domainSignals.sitemapXml ? `Found (${r.domainSignals.sitemapPages ?? "?"} pages)` : "Missing"}`,
  ];

  const lines: string[] = [
    `========================================`,
    `  GeoFast GEO Audit Report`,
    `========================================`,
    ``,
    `URL:      ${report.url}`,
    `Score:    ${report.overallScore}/100`,
    `Date:     ${new Date(report.createdAt).toLocaleString()}`,
    ``,
    `── Dimension Scores ──────────────────`,
    `  AI Crawlability:  ${r.scores.crawlability}/100`,
    `  AI Navigation:    ${r.scores.navigation}/100`,
    `  Structured Data:  ${r.scores.structured}/100`,
    `  Citability:       ${r.scores.citability}/100`,
    ``,
    `── Domain Signals ────────────────────`,
    ...signals.map((s) => `  ${s}`),
    ``,
    `── Issues (${r.issues.length}) ────────────────────`,
    ...formatIssues(r.issues),
    ``,
    `── Passed Checks (${r.passed.length}) ─────────────`,
    ...formatPassed(r.passed),
    ``,
    `── AI Perspective ────────────────────`,
    ...formatAIPerspective(r.llmPerspective),
    ``,
    `── E-E-A-T Assessment ────────────────`,
    ...formatEEAT(r.llmCitability?.eeat),
    ``,
    `========================================`,
    `  Generated by GeoFast (geofast.app)`,
    `========================================`,
  ];
  return lines.join("\n");
}

export function downloadTxt(report: StoredReport): void {
  const text = generateReportTxt(report);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `geofast-${report.domain}-${report.createdAt.split("T")[0]}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
